/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type CountryCode = string;
export interface CountryInfo { 'code' : CountryCode, 'name' : CountryName }
export type CountryName = string;
export type ExternalBlob = Uint8Array;
export type FormType = { 'contacto' : null } |
  { 'consultoria' : null } |
  { 'mentoria' : null };
export type ImageFormat = { 'jpg' : null } |
  { 'png' : null } |
  { 'webp' : null };
export type MessageStatus = { 'pending' : null } |
  { 'replied' : null };
export interface PublicVideoMeta {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'hasCustomThumbnail' : boolean,
  'sourceType' : { 'recorded' : null } |
    { 'uploaded' : null },
  'timestamp' : Time,
  'category' : VideoCategory,
}
export interface SectionVisit {
  'duration' : bigint,
  'country' : CountryInfo,
  'section' : string,
  'timestamp' : Time,
}
export interface StoredMessage {
  'id' : string,
  'status' : MessageStatus,
  'content' : string,
  'name' : string,
  'formType' : FormType,
  'email' : string,
  'timestamp' : Time,
  'reply' : [] | [string],
}
export interface ThumbnailMeta {
  'id' : string,
  'permanent' : boolean,
  'imageFormat' : { 'jpg' : null } |
    { 'png' : null } |
    { 'webp' : null },
  'fileSize' : bigint,
  'imageUrl' : string,
  'thumbnailType' : ThumbnailType,
  'timestamp' : Time,
  'dimensions' : { 'height' : bigint, 'width' : bigint },
  'videoId' : string,
}
export type ThumbnailType = { 'autoGenerated' : null } |
  { 'manualUpload' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoCategory = { 'acciones' : null } |
  { 'materiasPrimas' : null } |
  { 'divisas' : null } |
  { 'activosDigitales' : null } |
  { 'indices' : null };
export type VideoFileType = { 'avi' : null } |
  { 'mov' : null } |
  { 'mp4' : null } |
  { 'webm' : null };
export interface VideoMeta {
  'id' : string,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'thumbnailUrl' : [] | [string],
  'customThumbnail' : [] | [ExternalBlob],
  'blob' : ExternalBlob,
  'fileSize' : bigint,
  'sourceType' : { 'recorded' : null } |
    { 'uploaded' : null },
  'timestamp' : Time,
  'category' : VideoCategory,
}
export interface VideoViewRecord { 'country' : CountryInfo, 'timestamp' : Time }
export type PaymentServiceType = { 'consultoria' : null } |
  { 'mentoria' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'rejected' : null };
export interface PaymentRecord {
  'id' : string,
  'name' : string,
  'email' : string,
  'txnHash' : string,
  'amountIcp' : string,
  'serviceType' : PaymentServiceType,
  'status' : PaymentStatus,
  'timestamp' : Time,
  'notes' : [] | [string],
}

export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeleteVideos' : ActorMethod<[Array<string>], undefined>,
  'bulkMoveVideosToCategory' : ActorMethod<[Array<string>, string], undefined>,
  'bulkRecordViews' : ActorMethod<[Array<[string, CountryInfo]>], undefined>,
  'deleteCustomThumbnail' : ActorMethod<[string, string], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'downloadBlob' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'downloadVideoBlob' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getAdminPendingVideoMeta' : ActorMethod<[string], [] | [VideoMeta]>,
  'getAdminVideoMeta' : ActorMethod<[string], [] | [VideoMeta]>,
  'getAdminVideos' : ActorMethod<[], Array<VideoMeta>>,
  'getAdminVideosByCategory' : ActorMethod<[VideoCategory], Array<VideoMeta>>,
  'getAllVideos' : ActorMethod<[], Array<PublicVideoMeta>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomDomainStatus' : ActorMethod<
    [],
    {
      'status' : { 'verified' : null } |
        { 'pending' : null } |
        { 'notConfigured' : null } |
        { 'failed' : null },
      'token' : [] | [string],
      'lastAttempt' : [] | [Time],
    }
  >,
  'getMessages' : ActorMethod<[[] | [FormType]], Array<StoredMessage>>,
  'getPendingVideos' : ActorMethod<[], Array<VideoMeta>>,
  'getRecordingState' : ActorMethod<[], boolean>,
  'getSectionVisitRecords' : ActorMethod<[], Array<SectionVisit>>,
  'getThumbnailMeta' : ActorMethod<[string], [] | [ThumbnailMeta]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoMeta' : ActorMethod<[string], [] | [PublicVideoMeta]>,
  'getVideoThumbnailBlob' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getVideoThumbnails' : ActorMethod<[string], Array<string>>,
  'getVideosByCategory' : ActorMethod<[VideoCategory], Array<PublicVideoMeta>>,
  'getViewCount' : ActorMethod<[string], bigint>,
  'getViewRecords' : ActorMethod<[string], Array<VideoViewRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveVideoToCategory' : ActorMethod<[string, string], undefined>,
  'publishPendingVideo' : ActorMethod<[string], string>,
  'recordSectionVisit' : ActorMethod<[string, CountryInfo, bigint], undefined>,
  'recordView' : ActorMethod<[string, CountryInfo], undefined>,
  'replyToMessage' : ActorMethod<[string, string], undefined>,
  'retryVerification' : ActorMethod<[], undefined>,
  'revertToAutoThumbnail' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startRecording' : ActorMethod<[], undefined>,
  'stopRecording' : ActorMethod<[], undefined>,
  'streamVideo' : ActorMethod<
    [string, [] | [CountryInfo]],
    [] | [ExternalBlob]
  >,
  'submitContactForm' : ActorMethod<[ContactForm, FormType], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateVideoTitle' : ActorMethod<[string, string], undefined>,
  'uploadCustomThumbnail' : ActorMethod<
    [
      string,
      ExternalBlob,
      ImageFormat,
      { 'height' : bigint, 'width' : bigint },
      bigint,
    ],
    string
  >,
  'uploadManualVideo' : ActorMethod<
    [string, ExternalBlob, bigint, VideoCategory, VideoFileType],
    string
  >,
  'uploadThumbnail' : ActorMethod<
    [
      string,
      string,
      ThumbnailType,
      { 'height' : bigint, 'width' : bigint },
      bigint,
      { 'jpg' : null } |
        { 'png' : null } |
        { 'webp' : null },
    ],
    string
  >,
  'getPaymentRecords' : ActorMethod<[], Array<PaymentRecord>>,
  'submitPaymentRecord' : ActorMethod<[string, string, string, string, PaymentServiceType], string>,
  'updatePaymentStatus' : ActorMethod<[string, PaymentStatus, [] | [string]], undefined>,
  'uploadVideo' : ActorMethod<
    [string, ExternalBlob, bigint, VideoCategory],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];