/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const VideoCategory = IDL.Variant({
  'acciones' : IDL.Null,
  'materiasPrimas' : IDL.Null,
  'divisas' : IDL.Null,
  'activosDigitales' : IDL.Null,
  'indices' : IDL.Null,
});
export const VideoMeta = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'customThumbnail' : IDL.Opt(ExternalBlob),
  'blob' : ExternalBlob,
  'fileSize' : IDL.Nat,
  'sourceType' : IDL.Variant({ 'recorded' : IDL.Null, 'uploaded' : IDL.Null }),
  'timestamp' : Time,
  'category' : VideoCategory,
});
export const PublicVideoMeta = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'hasCustomThumbnail' : IDL.Bool,
  'sourceType' : IDL.Variant({ 'recorded' : IDL.Null, 'uploaded' : IDL.Null }),
  'timestamp' : Time,
  'category' : VideoCategory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FormType = IDL.Variant({
  'contacto' : IDL.Null,
  'consultoria' : IDL.Null,
  'mentoria' : IDL.Null,
});
export const MessageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'replied' : IDL.Null,
});
export const StoredMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'formType' : FormType,
  'email' : IDL.Text,
  'timestamp' : Time,
  'reply' : IDL.Opt(IDL.Text),
});
export const ThumbnailType = IDL.Variant({
  'autoGenerated' : IDL.Null,
  'manualUpload' : IDL.Null,
});
export const ThumbnailMeta = IDL.Record({
  'id' : IDL.Text,
  'permanent' : IDL.Bool,
  'imageFormat' : IDL.Variant({
    'jpg' : IDL.Null,
    'png' : IDL.Null,
    'webp' : IDL.Null,
  }),
  'fileSize' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'thumbnailType' : ThumbnailType,
  'timestamp' : Time,
  'dimensions' : IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
  'videoId' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ImageFormat = IDL.Variant({
  'jpg' : IDL.Null,
  'png' : IDL.Null,
  'webp' : IDL.Null,
});
export const VideoFileType = IDL.Variant({
  'avi' : IDL.Null,
  'mov' : IDL.Null,
  'mp4' : IDL.Null,
  'webm' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeleteVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkMoveVideosToCategory' : IDL.Func([IDL.Vec(IDL.Text), IDL.Text], [], []),
  'deleteCustomThumbnail' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'downloadBlob' : IDL.Func([ExternalBlob], [ExternalBlob], ['query']),
  'downloadVideoBlob' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getAdminPendingVideoMeta' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VideoMeta)],
      ['query'],
    ),
  'getAdminVideoMeta' : IDL.Func([IDL.Text], [IDL.Opt(VideoMeta)], ['query']),
  'getAdminVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
  'getAdminVideosByCategory' : IDL.Func(
      [VideoCategory],
      [IDL.Vec(VideoMeta)],
      ['query'],
    ),
  'getAllVideos' : IDL.Func([], [IDL.Vec(PublicVideoMeta)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomDomainStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'status' : IDL.Variant({
            'verified' : IDL.Null,
            'pending' : IDL.Null,
            'notConfigured' : IDL.Null,
            'failed' : IDL.Null,
          }),
          'token' : IDL.Opt(IDL.Text),
          'lastAttempt' : IDL.Opt(Time),
        }),
      ],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Opt(FormType)],
      [IDL.Vec(StoredMessage)],
      ['query'],
    ),
  'getPendingVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
  'getRecordingState' : IDL.Func([], [IDL.Bool], ['query']),
  'getThumbnailMeta' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ThumbnailMeta)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoMeta' : IDL.Func([IDL.Text], [IDL.Opt(PublicVideoMeta)], ['query']),
  'getVideoThumbnailBlob' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getVideoThumbnails' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getVideosByCategory' : IDL.Func(
      [VideoCategory],
      [IDL.Vec(PublicVideoMeta)],
      ['query'],
    ),
  'getViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moveVideoToCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'publishPendingVideo' : IDL.Func([IDL.Text], [IDL.Text], []),
  'replyToMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'retryVerification' : IDL.Func([], [], []),
  'revertToAutoThumbnail' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startRecording' : IDL.Func([], [], []),
  'stopRecording' : IDL.Func([], [], []),
  'streamVideo' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], []),
  'submitContactForm' : IDL.Func([ContactForm, FormType], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateVideoTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadCustomThumbnail' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        ImageFormat,
        IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'uploadManualVideo' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Nat, VideoCategory, VideoFileType],
      [IDL.Text],
      [],
    ),
  'uploadThumbnail' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ThumbnailType,
        IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
        IDL.Nat,
        IDL.Variant({ 'jpg' : IDL.Null, 'png' : IDL.Null, 'webp' : IDL.Null }),
      ],
      [IDL.Text],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Nat, VideoCategory],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const VideoCategory = IDL.Variant({
    'acciones' : IDL.Null,
    'materiasPrimas' : IDL.Null,
    'divisas' : IDL.Null,
    'activosDigitales' : IDL.Null,
    'indices' : IDL.Null,
  });
  const VideoMeta = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'customThumbnail' : IDL.Opt(ExternalBlob),
    'blob' : ExternalBlob,
    'fileSize' : IDL.Nat,
    'sourceType' : IDL.Variant({
      'recorded' : IDL.Null,
      'uploaded' : IDL.Null,
    }),
    'timestamp' : Time,
    'category' : VideoCategory,
  });
  const PublicVideoMeta = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'hasCustomThumbnail' : IDL.Bool,
    'sourceType' : IDL.Variant({
      'recorded' : IDL.Null,
      'uploaded' : IDL.Null,
    }),
    'timestamp' : Time,
    'category' : VideoCategory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FormType = IDL.Variant({
    'contacto' : IDL.Null,
    'consultoria' : IDL.Null,
    'mentoria' : IDL.Null,
  });
  const MessageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'replied' : IDL.Null,
  });
  const StoredMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'formType' : FormType,
    'email' : IDL.Text,
    'timestamp' : Time,
    'reply' : IDL.Opt(IDL.Text),
  });
  const ThumbnailType = IDL.Variant({
    'autoGenerated' : IDL.Null,
    'manualUpload' : IDL.Null,
  });
  const ThumbnailMeta = IDL.Record({
    'id' : IDL.Text,
    'permanent' : IDL.Bool,
    'imageFormat' : IDL.Variant({
      'jpg' : IDL.Null,
      'png' : IDL.Null,
      'webp' : IDL.Null,
    }),
    'fileSize' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'thumbnailType' : ThumbnailType,
    'timestamp' : Time,
    'dimensions' : IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
    'videoId' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ImageFormat = IDL.Variant({
    'jpg' : IDL.Null,
    'png' : IDL.Null,
    'webp' : IDL.Null,
  });
  const VideoFileType = IDL.Variant({
    'avi' : IDL.Null,
    'mov' : IDL.Null,
    'mp4' : IDL.Null,
    'webm' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeleteVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkMoveVideosToCategory' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'deleteCustomThumbnail' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'downloadBlob' : IDL.Func([ExternalBlob], [ExternalBlob], ['query']),
    'downloadVideoBlob' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getAdminPendingVideoMeta' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoMeta)],
        ['query'],
      ),
    'getAdminVideoMeta' : IDL.Func([IDL.Text], [IDL.Opt(VideoMeta)], ['query']),
    'getAdminVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
    'getAdminVideosByCategory' : IDL.Func(
        [VideoCategory],
        [IDL.Vec(VideoMeta)],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(PublicVideoMeta)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomDomainStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'status' : IDL.Variant({
              'verified' : IDL.Null,
              'pending' : IDL.Null,
              'notConfigured' : IDL.Null,
              'failed' : IDL.Null,
            }),
            'token' : IDL.Opt(IDL.Text),
            'lastAttempt' : IDL.Opt(Time),
          }),
        ],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Opt(FormType)],
        [IDL.Vec(StoredMessage)],
        ['query'],
      ),
    'getPendingVideos' : IDL.Func([], [IDL.Vec(VideoMeta)], ['query']),
    'getRecordingState' : IDL.Func([], [IDL.Bool], ['query']),
    'getThumbnailMeta' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ThumbnailMeta)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoMeta' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicVideoMeta)],
        ['query'],
      ),
    'getVideoThumbnailBlob' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getVideoThumbnails' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getVideosByCategory' : IDL.Func(
        [VideoCategory],
        [IDL.Vec(PublicVideoMeta)],
        ['query'],
      ),
    'getViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moveVideoToCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'publishPendingVideo' : IDL.Func([IDL.Text], [IDL.Text], []),
    'replyToMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'retryVerification' : IDL.Func([], [], []),
    'revertToAutoThumbnail' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startRecording' : IDL.Func([], [], []),
    'stopRecording' : IDL.Func([], [], []),
    'streamVideo' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], []),
    'submitContactForm' : IDL.Func([ContactForm, FormType], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateVideoTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadCustomThumbnail' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          ImageFormat,
          IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'uploadManualVideo' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Nat, VideoCategory, VideoFileType],
        [IDL.Text],
        [],
      ),
    'uploadThumbnail' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ThumbnailType,
          IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
          IDL.Nat,
          IDL.Variant({
            'jpg' : IDL.Null,
            'png' : IDL.Null,
            'webp' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Nat, VideoCategory],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };