import type { Principal } from "@icp-sdk/core/principal";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export class ExternalBlob {
    getBytes(): Promise<Uint8Array<ArrayBuffer>>;
    getDirectURL(): string;
    static fromURL(url: string): ExternalBlob;
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob;
    withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface StoredMessage {
    id: string;
    status: MessageStatus;
    content: string;
    name: string;
    formType: FormType;
    email: string;
    timestamp: Time;
    reply?: string;
}
export interface PublicVideoMeta {
    id: string;
    title: string;
    thumbnailUrl?: string;
    hasCustomThumbnail: boolean;
    sourceType: Variant_recorded_uploaded;
    timestamp: Time;
    category: VideoCategory;
}
export interface PaymentRecord {
    id: string;
    status: PaymentStatus;
    serviceType: PaymentServiceType;
    name: string;
    txnDate: string;
    txnHash: string;
    email: string;
    notes?: string;
    timestamp: Time;
    amountIcp: string;
}
export interface VideoMeta {
    id: string;
    title: string;
    thumbnail?: ExternalBlob;
    thumbnailUrl?: string;
    customThumbnail?: ExternalBlob;
    blob: ExternalBlob;
    fileSize: bigint;
    sourceType: Variant_recorded_uploaded;
    timestamp: Time;
    category: VideoCategory;
}
export interface ContactForm {
    name: string;
    email: string;
    message: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface BankTransferRecord {
    id: string;
    status: PaymentStatus;
    serviceType: PaymentServiceType;
    transferDate: string;
    name: string;
    email: string;
    bankName: string;
    referenceNote: string;
    notes?: string;
    timestamp: Time;
    amountUsd: string;
}
export type CountryCode = string;
export interface ThumbnailMeta {
    id: string;
    permanent: boolean;
    imageFormat: ImageFormat;
    fileSize: bigint;
    imageUrl: string;
    thumbnailType: ThumbnailType;
    timestamp: Time;
    dimensions: {
        height: bigint;
        width: bigint;
    };
    videoId: string;
}
export interface SectionVisit {
    duration: bigint;
    country: CountryInfo;
    section: string;
    timestamp: Time;
}
export interface VideoViewRecord {
    country: CountryInfo;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CountryInfo {
    code: CountryCode;
    name: CountryName;
}
export type CountryName = string;
export interface UserProfile {
    name: string;
}
export enum FormType {
    contacto = "contacto",
    consultoria = "consultoria",
    mentoria = "mentoria"
}
export enum ImageFormat {
    jpg = "jpg",
    png = "png",
    webp = "webp"
}
export enum MessageStatus {
    pending = "pending",
    replied = "replied"
}
export enum PaymentServiceType {
    consultoria = "consultoria",
    mentoria = "mentoria"
}
export enum PaymentStatus {
    pending = "pending",
    rejected = "rejected",
    confirmed = "confirmed"
}
export enum ThumbnailType {
    autoGenerated = "autoGenerated",
    manualUpload = "manualUpload"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_recorded_uploaded {
    recorded = "recorded",
    uploaded = "uploaded"
}
export enum Variant_verified_pending_notConfigured_failed {
    verified = "verified",
    pending = "pending",
    notConfigured = "notConfigured",
    failed = "failed"
}
export enum VideoCategory {
    acciones = "acciones",
    materiasPrimas = "materiasPrimas",
    divisas = "divisas",
    activosDigitales = "activosDigitales",
    indices = "indices"
}
export enum VideoFileType {
    avi = "avi",
    mov = "mov",
    mp4 = "mp4",
    webm = "webm"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkDeleteVideos(videoIds: Array<string>): Promise<void>;
    bulkMoveVideosToCategory(videoIds: Array<string>, newCategoryText: string): Promise<void>;
    bulkRecordViews(viewEntries: Array<[string, CountryInfo]>): Promise<void>;
    deleteBankTransferRecord(transferId: string): Promise<void>;
    deleteCustomThumbnail(videoId: string, thumbnailId: string): Promise<void>;
    deleteMessage(messageId: string): Promise<void>;
    deletePaymentRecord(paymentId: string): Promise<void>;
    deleteSectionVisitRecord(visitId: bigint): Promise<void>;
    deleteVideo(videoId: string): Promise<void>;
    downloadBlob(blob: ExternalBlob): Promise<ExternalBlob>;
    downloadVideoBlob(videoId: string): Promise<ExternalBlob | null>;
    getAdminPendingVideoMeta(pendingVideoId: string): Promise<VideoMeta | null>;
    getAdminVideoMeta(videoId: string): Promise<VideoMeta | null>;
    getAdminVideos(): Promise<Array<VideoMeta>>;
    getAdminVideosByCategory(category: VideoCategory): Promise<Array<VideoMeta>>;
    getAllVideos(): Promise<Array<PublicVideoMeta>>;
    getBankTransferRecords(): Promise<Array<BankTransferRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomDomainStatus(): Promise<{
        status: Variant_verified_pending_notConfigured_failed;
        token?: string;
        lastAttempt?: Time;
    }>;
    getMessages(formType: FormType | null): Promise<Array<StoredMessage>>;
    getPaymentRecords(): Promise<Array<PaymentRecord>>;
    getPendingVideos(): Promise<Array<VideoMeta>>;
    getRecordingState(): Promise<boolean>;
    getSectionVisitRecords(): Promise<Array<[bigint, SectionVisit]>>;
    getThumbnailMeta(thumbnailId: string): Promise<ThumbnailMeta | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoMeta(videoId: string): Promise<PublicVideoMeta | null>;
    getVideoThumbnailBlob(videoId: string): Promise<ExternalBlob | null>;
    getVideoThumbnails(videoId: string): Promise<Array<string>>;
    getVideosByCategory(category: VideoCategory): Promise<Array<PublicVideoMeta>>;
    getViewCount(videoId: string): Promise<bigint>;
    getViewRecords(videoId: string): Promise<Array<VideoViewRecord>>;
    isCallerAdmin(): Promise<boolean>;
    moveVideoToCategory(videoId: string, newCategoryText: string): Promise<void>;
    publishPendingVideo(pendingVideoId: string): Promise<string>;
    recordSectionVisit(section: string, country: CountryInfo, duration: bigint): Promise<void>;
    recordView(videoId: string, country: CountryInfo): Promise<void>;
    replyToMessage(messageId: string, replyText: string): Promise<void>;
    retryVerification(): Promise<void>;
    revertToAutoThumbnail(videoId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startRecording(): Promise<void>;
    stopRecording(): Promise<void>;
    streamVideo(videoId: string, country: CountryInfo | null): Promise<ExternalBlob | null>;
    submitBankTransferRecord(name: string, email: string, amountUsd: string, bankName: string, transferDate: string, referenceNote: string, serviceType: PaymentServiceType): Promise<string>;
    submitContactForm(form: ContactForm, formType: FormType): Promise<string>;
    submitPaymentRecord(name: string, email: string, txnHash: string, amountIcp: string, txnDate: string, serviceType: PaymentServiceType): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBankTransferStatus(transferId: string, newStatus: PaymentStatus, adminNotes: string | null): Promise<void>;
    updatePaymentStatus(paymentId: string, newStatus: PaymentStatus, notes: string | null): Promise<void>;
    updateVideoTitle(videoId: string, newTitle: string): Promise<void>;
    uploadCustomThumbnail(videoId: string, thumbnailBlob: ExternalBlob, imageFormat: ImageFormat, dimensions: {
        height: bigint;
        width: bigint;
    }, fileSize: bigint): Promise<string>;
    uploadManualVideo(title: string, blob: ExternalBlob, fileSize: bigint, category: VideoCategory, _fileType: VideoFileType): Promise<string>;
    uploadManualVideoWithDate(title: string, blob: ExternalBlob, fileSize: bigint, category: VideoCategory, _fileType: VideoFileType, customTimestamp: bigint | null): Promise<string>;
    uploadThumbnail(videoId: string, imageUrl: string, thumbnailType: ThumbnailType, dimensions: {
        height: bigint;
        width: bigint;
    }, fileSize: bigint, _imageFormat: ImageFormat): Promise<string>;
    uploadVideo(title: string, blob: ExternalBlob, fileSize: bigint, category: VideoCategory): Promise<string>;
}
