/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface StoredMessage {
    id: string;
    status: MessageStatus;
    content: string;
    name: string;
    formType: FormType;
    email: string;
    timestamp: Time;
    reply?: string;
}
export interface PublicVideoMeta {
    id: string;
    title: string;
    thumbnailUrl?: string;
    hasCustomThumbnail: boolean;
    sourceType: Variant_recorded_uploaded;
    timestamp: Time;
    category: VideoCategory;
}
export interface PaymentRecord {
    id: string;
    status: PaymentStatus;
    serviceType: PaymentServiceType;
    name: string;
    txnDate: string;
    txnHash: string;
    email: string;
    notes?: string;
    timestamp: Time;
    amountIcp: string;
}
export interface VideoMeta {
    id: string;
    title: string;
    thumbnail?: ExternalBlob;
    thumbnailUrl?: string;
    customThumbnail?: ExternalBlob;
    blob: ExternalBlob;
    fileSize: bigint;
    sourceType: Variant_recorded_uploaded;
    timestamp: Time;
    category: VideoCategory;
}
export interface ContactForm {
    name: string;
    email: string;
    message: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type CountryCode = string;
export interface ThumbnailMeta {
    id: string;
    permanent: boolean;
    imageFormat: ImageFormat;
    fileSize: bigint;
    imageUrl: string;
    thumbnailType: ThumbnailType;
    timestamp: Time;
    dimensions: {
        height: bigint;
        width: bigint;
    };
    videoId: string;
}
export interface SectionVisit {
    duration: bigint;
    country: CountryInfo;
    section: string;
    timestamp: Time;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface VideoViewRecord {
    country: CountryInfo;
    timestamp: Time;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CountryInfo {
    code: CountryCode;
    name: CountryName;
}
export type CountryName = string;
export interface UserProfile {
    name: string;
}
export enum FormType {
    contacto = "contacto",
    consultoria = "consultoria",
    mentoria = "mentoria"
}
export enum ImageFormat {
    jpg = "jpg",
    png = "png",
    webp = "webp"
}
export enum MessageStatus {
    pending = "pending",
    replied = "replied"
}
export enum PaymentServiceType {
    consultoria = "consultoria",
    mentoria = "mentoria"
}
export enum PaymentStatus {
    pending = "pending",
    rejected = "rejected",
    confirmed = "confirmed"
}
export enum ThumbnailType {
    autoGenerated = "autoGenerated",
    manualUpload = "manualUpload"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_recorded_uploaded {
    recorded = "recorded",
    uploaded = "uploaded"
}
export enum Variant_verified_pending_notConfigured_failed {
    verified = "verified",
    pending = "pending",
    notConfigured = "notConfigured",
    failed = "failed"
}
export enum VideoCategory {
    acciones = "acciones",
    materiasPrimas = "materiasPrimas",
    divisas = "divisas",
    activosDigitales = "activosDigitales",
    indices = "indices"
}
export enum VideoFileType {
    avi = "avi",
    mov = "mov",
    mp4 = "mp4",
    webm = "webm"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkDeleteVideos(videoIds: Array<string>): Promise<void>;
    bulkMoveVideosToCategory(videoIds: Array<string>, newCategoryText: string): Promise<void>;
    bulkRecordViews(viewEntries: Array<[string, CountryInfo]>): Promise<void>;
    deleteCustomThumbnail(videoId: string, thumbnailId: string): Promise<void>;
    deleteMessage(messageId: string): Promise<void>;
    deletePaymentRecord(paymentId: string): Promise<void>;
    deleteSectionVisitRecord(visitId: bigint): Promise<void>;
    deleteVideo(videoId: string): Promise<void>;
    downloadBlob(blob: ExternalBlob): Promise<ExternalBlob>;
    downloadVideoBlob(videoId: string): Promise<ExternalBlob | null>;
    getAdminPendingVideoMeta(pendingVideoId: string): Promise<VideoMeta | null>;
    getAdminVideoMeta(videoId: string): Promise<VideoMeta | null>;
    getAdminVideos(): Promise<Array<VideoMeta>>;
    getAdminVideosByCategory(category: VideoCategory): Promise<Array<VideoMeta>>;
    getAllVideos(): Promise<Array<PublicVideoMeta>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomDomainStatus(): Promise<{
        status: Variant_verified_pending_notConfigured_failed;
        token?: string;
        lastAttempt?: Time;
    }>;
    getMessages(formType: FormType | null): Promise<Array<StoredMessage>>;
    getPaymentRecords(): Promise<Array<PaymentRecord>>;
    getPendingVideos(): Promise<Array<VideoMeta>>;
    getRecordingState(): Promise<boolean>;
    getSectionVisitRecords(): Promise<Array<[bigint, SectionVisit]>>;
    getThumbnailMeta(thumbnailId: string): Promise<ThumbnailMeta | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoMeta(videoId: string): Promise<PublicVideoMeta | null>;
    getVideoThumbnailBlob(videoId: string): Promise<ExternalBlob | null>;
    getVideoThumbnails(videoId: string): Promise<Array<string>>;
    getVideosByCategory(category: VideoCategory): Promise<Array<PublicVideoMeta>>;
    getViewCount(videoId: string): Promise<bigint>;
    getViewRecords(videoId: string): Promise<Array<VideoViewRecord>>;
    isCallerAdmin(): Promise<boolean>;
    moveVideoToCategory(videoId: string, newCategoryText: string): Promise<void>;
    publishPendingVideo(pendingVideoId: string): Promise<string>;
    recordSectionVisit(section: string, country: CountryInfo, duration: bigint): Promise<void>;
    recordView(videoId: string, country: CountryInfo): Promise<void>;
    replyToMessage(messageId: string, replyText: string): Promise<void>;
    retryVerification(): Promise<void>;
    revertToAutoThumbnail(videoId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startRecording(): Promise<void>;
    stopRecording(): Promise<void>;
    streamVideo(videoId: string, country: CountryInfo | null): Promise<ExternalBlob | null>;
    submitContactForm(form: ContactForm, formType: FormType): Promise<string>;
    submitPaymentRecord(name: string, email: string, txnHash: string, amountIcp: string, txnDate: string, serviceType: PaymentServiceType): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePaymentStatus(paymentId: string, newStatus: PaymentStatus, notes: string | null): Promise<void>;
    updateVideoTitle(videoId: string, newTitle: string): Promise<void>;
    uploadCustomThumbnail(videoId: string, thumbnailBlob: ExternalBlob, imageFormat: ImageFormat, dimensions: {
        height: bigint;
        width: bigint;
    }, fileSize: bigint): Promise<string>;
    uploadManualVideo(title: string, blob: ExternalBlob, fileSize: bigint, category: VideoCategory, _fileType: VideoFileType): Promise<string>;
    uploadManualVideoWithDate(title: string, blob: ExternalBlob, fileSize: bigint, category: VideoCategory, _fileType: VideoFileType, customTimestamp: bigint | null): Promise<string>;
    uploadThumbnail(videoId: string, imageUrl: string, thumbnailType: ThumbnailType, dimensions: {
        height: bigint;
        width: bigint;
    }, fileSize: bigint, _imageFormat: ImageFormat): Promise<string>;
    uploadVideo(title: string, blob: ExternalBlob, fileSize: bigint, category: VideoCategory): Promise<string>;
}
import type { CountryInfo as _CountryInfo, ExternalBlob as _ExternalBlob, FormType as _FormType, ImageFormat as _ImageFormat, MessageStatus as _MessageStatus, PaymentRecord as _PaymentRecord, PaymentServiceType as _PaymentServiceType, PaymentStatus as _PaymentStatus, PublicVideoMeta as _PublicVideoMeta, StoredMessage as _StoredMessage, ThumbnailMeta as _ThumbnailMeta, ThumbnailType as _ThumbnailType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoCategory as _VideoCategory, VideoFileType as _VideoFileType, VideoMeta as _VideoMeta, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkDeleteVideos(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteVideos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteVideos(arg0);
            return result;
        }
    }
    async bulkMoveVideosToCategory(arg0: Array<string>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkMoveVideosToCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkMoveVideosToCategory(arg0, arg1);
            return result;
        }
    }
    async bulkRecordViews(arg0: Array<[string, CountryInfo]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkRecordViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkRecordViews(arg0);
            return result;
        }
    }
    async deleteCustomThumbnail(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomThumbnail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomThumbnail(arg0, arg1);
            return result;
        }
    }
    async deleteMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deletePaymentRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePaymentRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePaymentRecord(arg0);
            return result;
        }
    }
    async deleteSectionVisitRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSectionVisitRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSectionVisitRecord(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async downloadBlob(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadBlob(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadBlob(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async downloadVideoBlob(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadVideoBlob(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadVideoBlob(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPendingVideoMeta(arg0: string): Promise<VideoMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPendingVideoMeta(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPendingVideoMeta(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminVideoMeta(arg0: string): Promise<VideoMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminVideoMeta(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminVideoMeta(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminVideos(): Promise<Array<VideoMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminVideos();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminVideos();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminVideosByCategory(arg0: VideoCategory): Promise<Array<VideoMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminVideosByCategory(to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminVideosByCategory(to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideos(): Promise<Array<PublicVideoMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomDomainStatus(): Promise<{
        status: Variant_verified_pending_notConfigured_failed;
        token?: string;
        lastAttempt?: Time;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomDomainStatus();
                return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomDomainStatus();
            return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: FormType | null): Promise<Array<StoredMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentRecords(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecords();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecords();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingVideos(): Promise<Array<VideoMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingVideos();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingVideos();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecordingState(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordingState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordingState();
            return result;
        }
    }
    async getSectionVisitRecords(): Promise<Array<[bigint, SectionVisit]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionVisitRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionVisitRecords();
            return result;
        }
    }
    async getThumbnailMeta(arg0: string): Promise<ThumbnailMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThumbnailMeta(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThumbnailMeta(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoMeta(arg0: string): Promise<PublicVideoMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoMeta(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoMeta(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoThumbnailBlob(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoThumbnailBlob(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoThumbnailBlob(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoThumbnails(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoThumbnails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoThumbnails(arg0);
            return result;
        }
    }
    async getVideosByCategory(arg0: VideoCategory): Promise<Array<PublicVideoMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getViewCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewCount(arg0);
            return result;
        }
    }
    async getViewRecords(arg0: string): Promise<Array<VideoViewRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewRecords(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async moveVideoToCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveVideoToCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveVideoToCategory(arg0, arg1);
            return result;
        }
    }
    async publishPendingVideo(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.publishPendingVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishPendingVideo(arg0);
            return result;
        }
    }
    async recordSectionVisit(arg0: string, arg1: CountryInfo, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSectionVisit(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSectionVisit(arg0, arg1, arg2);
            return result;
        }
    }
    async recordView(arg0: string, arg1: CountryInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordView(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordView(arg0, arg1);
            return result;
        }
    }
    async replyToMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToMessage(arg0, arg1);
            return result;
        }
    }
    async retryVerification(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.retryVerification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryVerification();
            return result;
        }
    }
    async revertToAutoThumbnail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revertToAutoThumbnail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revertToAutoThumbnail(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async startRecording(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startRecording();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRecording();
            return result;
        }
    }
    async stopRecording(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopRecording();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopRecording();
            return result;
        }
    }
    async streamVideo(arg0: string, arg1: CountryInfo | null): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.streamVideo(arg0, to_candid_opt_n56(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.streamVideo(arg0, to_candid_opt_n56(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: ContactForm, arg1: FormType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, to_candid_FormType_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, to_candid_FormType_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitPaymentRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: PaymentServiceType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentRecord(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentServiceType_n57(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentRecord(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentServiceType_n57(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: PaymentStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n59(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n61(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n59(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n61(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateVideoTitle(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoTitle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoTitle(arg0, arg1);
            return result;
        }
    }
    async uploadCustomThumbnail(arg0: string, arg1: ExternalBlob, arg2: ImageFormat, arg3: {
        height: bigint;
        width: bigint;
    }, arg4: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCustomThumbnail(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), to_candid_ImageFormat_n62(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCustomThumbnail(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), to_candid_ImageFormat_n62(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async uploadManualVideo(arg0: string, arg1: ExternalBlob, arg2: bigint, arg3: VideoCategory, arg4: VideoFileType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadManualVideo(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg3), to_candid_VideoFileType_n64(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadManualVideo(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg3), to_candid_VideoFileType_n64(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async uploadManualVideoWithDate(arg0: string, arg1: ExternalBlob, arg2: bigint, arg3: VideoCategory, arg4: VideoFileType, arg5: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadManualVideoWithDate(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg3), to_candid_VideoFileType_n64(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n66(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadManualVideoWithDate(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg3), to_candid_VideoFileType_n64(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n66(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async uploadThumbnail(arg0: string, arg1: string, arg2: ThumbnailType, arg3: {
        height: bigint;
        width: bigint;
    }, arg4: bigint, arg5: ImageFormat): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadThumbnail(arg0, arg1, to_candid_ThumbnailType_n67(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_variant_n63(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadThumbnail(arg0, arg1, to_candid_ThumbnailType_n67(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_variant_n63(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async uploadVideo(arg0: string, arg1: ExternalBlob, arg2: bigint, arg3: VideoCategory): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_VideoCategory_n21(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FormType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormType): FormType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentServiceType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentServiceType): PaymentServiceType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PublicVideoMeta_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicVideoMeta): PublicVideoMeta {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StoredMessage_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoredMessage): StoredMessage {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ThumbnailMeta_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThumbnailMeta): ThumbnailMeta {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ThumbnailType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThumbnailType): ThumbnailType {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_VideoCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoCategory): VideoCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoMeta_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMeta): Promise<VideoMeta> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoMeta]): Promise<VideoMeta | null> {
    return value.length === 0 ? null : await from_candid_VideoMeta_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ThumbnailMeta]): ThumbnailMeta | null {
    return value.length === 0 ? null : from_candid_ThumbnailMeta_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicVideoMeta]): PublicVideoMeta | null {
    return value.length === 0 ? null : from_candid_PublicVideoMeta_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    thumbnailUrl: [] | [string];
    customThumbnail: [] | [_ExternalBlob];
    blob: _ExternalBlob;
    fileSize: bigint;
    sourceType: {
        recorded: null;
    } | {
        uploaded: null;
    };
    timestamp: _Time;
    category: _VideoCategory;
}): Promise<{
    id: string;
    title: string;
    thumbnail?: ExternalBlob;
    thumbnailUrl?: string;
    customThumbnail?: ExternalBlob;
    blob: ExternalBlob;
    fileSize: bigint;
    sourceType: Variant_recorded_uploaded;
    timestamp: Time;
    category: VideoCategory;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.thumbnail)),
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.thumbnailUrl)),
        customThumbnail: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.customThumbnail)),
        blob: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob),
        fileSize: value.fileSize,
        sourceType: from_candid_variant_n17(_uploadFile, _downloadFile, value.sourceType),
        timestamp: value.timestamp,
        category: from_candid_VideoCategory_n18(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnailUrl: [] | [string];
    hasCustomThumbnail: boolean;
    sourceType: {
        recorded: null;
    } | {
        uploaded: null;
    };
    timestamp: _Time;
    category: _VideoCategory;
}): {
    id: string;
    title: string;
    thumbnailUrl?: string;
    hasCustomThumbnail: boolean;
    sourceType: Variant_recorded_uploaded;
    timestamp: Time;
    category: VideoCategory;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.thumbnailUrl)),
        hasCustomThumbnail: value.hasCustomThumbnail,
        sourceType: from_candid_variant_n17(_uploadFile, _downloadFile, value.sourceType),
        timestamp: value.timestamp,
        category: from_candid_VideoCategory_n18(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        verified: null;
    } | {
        pending: null;
    } | {
        notConfigured: null;
    } | {
        failed: null;
    };
    token: [] | [string];
    lastAttempt: [] | [_Time];
}): {
    status: Variant_verified_pending_notConfigured_failed;
    token?: string;
    lastAttempt?: Time;
} {
    return {
        status: from_candid_variant_n30(_uploadFile, _downloadFile, value.status),
        token: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.token)),
        lastAttempt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.lastAttempt))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MessageStatus;
    content: string;
    name: string;
    formType: _FormType;
    email: string;
    timestamp: _Time;
    reply: [] | [string];
}): {
    id: string;
    status: MessageStatus;
    content: string;
    name: string;
    formType: FormType;
    email: string;
    timestamp: Time;
    reply?: string;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n38(_uploadFile, _downloadFile, value.status),
        content: value.content,
        name: value.name,
        formType: from_candid_FormType_n40(_uploadFile, _downloadFile, value.formType),
        email: value.email,
        timestamp: value.timestamp,
        reply: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.reply))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    serviceType: _PaymentServiceType;
    name: string;
    txnDate: string;
    txnHash: string;
    email: string;
    notes: [] | [string];
    timestamp: _Time;
    amountIcp: string;
}): {
    id: string;
    status: PaymentStatus;
    serviceType: PaymentServiceType;
    name: string;
    txnDate: string;
    txnHash: string;
    email: string;
    notes?: string;
    timestamp: Time;
    amountIcp: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n45(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_PaymentServiceType_n47(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        txnDate: value.txnDate,
        txnHash: value.txnHash,
        email: value.email,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        amountIcp: value.amountIcp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    permanent: boolean;
    imageFormat: {
        jpg: null;
    } | {
        png: null;
    } | {
        webp: null;
    };
    fileSize: bigint;
    imageUrl: string;
    thumbnailType: _ThumbnailType;
    timestamp: _Time;
    dimensions: {
        height: bigint;
        width: bigint;
    };
    videoId: string;
}): {
    id: string;
    permanent: boolean;
    imageFormat: ImageFormat;
    fileSize: bigint;
    imageUrl: string;
    thumbnailType: ThumbnailType;
    timestamp: Time;
    dimensions: {
        height: bigint;
        width: bigint;
    };
    videoId: string;
} {
    return {
        id: value.id,
        permanent: value.permanent,
        imageFormat: from_candid_variant_n52(_uploadFile, _downloadFile, value.imageFormat),
        fileSize: value.fileSize,
        imageUrl: value.imageUrl,
        thumbnailType: from_candid_ThumbnailType_n53(_uploadFile, _downloadFile, value.thumbnailType),
        timestamp: value.timestamp,
        dimensions: value.dimensions,
        videoId: value.videoId
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recorded: null;
} | {
    uploaded: null;
}): Variant_recorded_uploaded {
    return "recorded" in value ? Variant_recorded_uploaded.recorded : "uploaded" in value ? Variant_recorded_uploaded.uploaded : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    acciones: null;
} | {
    materiasPrimas: null;
} | {
    divisas: null;
} | {
    activosDigitales: null;
} | {
    indices: null;
}): VideoCategory {
    return "acciones" in value ? VideoCategory.acciones : "materiasPrimas" in value ? VideoCategory.materiasPrimas : "divisas" in value ? VideoCategory.divisas : "activosDigitales" in value ? VideoCategory.activosDigitales : "indices" in value ? VideoCategory.indices : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    notConfigured: null;
} | {
    failed: null;
}): Variant_verified_pending_notConfigured_failed {
    return "verified" in value ? Variant_verified_pending_notConfigured_failed.verified : "pending" in value ? Variant_verified_pending_notConfigured_failed.pending : "notConfigured" in value ? Variant_verified_pending_notConfigured_failed.notConfigured : "failed" in value ? Variant_verified_pending_notConfigured_failed.failed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    replied: null;
}): MessageStatus {
    return "pending" in value ? MessageStatus.pending : "replied" in value ? MessageStatus.replied : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contacto: null;
} | {
    consultoria: null;
} | {
    mentoria: null;
}): FormType {
    return "contacto" in value ? FormType.contacto : "consultoria" in value ? FormType.consultoria : "mentoria" in value ? FormType.mentoria : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    confirmed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "rejected" in value ? PaymentStatus.rejected : "confirmed" in value ? PaymentStatus.confirmed : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    consultoria: null;
} | {
    mentoria: null;
}): PaymentServiceType {
    return "consultoria" in value ? PaymentServiceType.consultoria : "mentoria" in value ? PaymentServiceType.mentoria : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jpg: null;
} | {
    png: null;
} | {
    webp: null;
}): ImageFormat {
    return "jpg" in value ? ImageFormat.jpg : "png" in value ? ImageFormat.png : "webp" in value ? ImageFormat.webp : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoGenerated: null;
} | {
    manualUpload: null;
}): ThumbnailType {
    return "autoGenerated" in value ? ThumbnailType.autoGenerated : "manualUpload" in value ? ThumbnailType.manualUpload : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoMeta>): Promise<Array<VideoMeta>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoMeta_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicVideoMeta>): Array<PublicVideoMeta> {
    return value.map((x)=>from_candid_PublicVideoMeta_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoredMessage>): Array<StoredMessage> {
    return value.map((x)=>from_candid_StoredMessage_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n43(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FormType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormType): _FormType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_ImageFormat_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageFormat): _ImageFormat {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentServiceType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentServiceType): _PaymentServiceType {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_ThumbnailType_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThumbnailType): _ThumbnailType {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoCategory): _VideoCategory {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_VideoFileType_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoFileType): _VideoFileType {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormType | null): [] | [_FormType] {
    return value === null ? candid_none() : candid_some(to_candid_FormType_n33(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CountryInfo | null): [] | [_CountryInfo] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoCategory): {
    acciones: null;
} | {
    materiasPrimas: null;
} | {
    divisas: null;
} | {
    activosDigitales: null;
} | {
    indices: null;
} {
    return value == VideoCategory.acciones ? {
        acciones: null
    } : value == VideoCategory.materiasPrimas ? {
        materiasPrimas: null
    } : value == VideoCategory.divisas ? {
        divisas: null
    } : value == VideoCategory.activosDigitales ? {
        activosDigitales: null
    } : value == VideoCategory.indices ? {
        indices: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormType): {
    contacto: null;
} | {
    consultoria: null;
} | {
    mentoria: null;
} {
    return value == FormType.contacto ? {
        contacto: null
    } : value == FormType.consultoria ? {
        consultoria: null
    } : value == FormType.mentoria ? {
        mentoria: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentServiceType): {
    consultoria: null;
} | {
    mentoria: null;
} {
    return value == PaymentServiceType.consultoria ? {
        consultoria: null
    } : value == PaymentServiceType.mentoria ? {
        mentoria: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    confirmed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.rejected ? {
        rejected: null
    } : value == PaymentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageFormat): {
    jpg: null;
} | {
    png: null;
} | {
    webp: null;
} {
    return value == ImageFormat.jpg ? {
        jpg: null
    } : value == ImageFormat.png ? {
        png: null
    } : value == ImageFormat.webp ? {
        webp: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoFileType): {
    avi: null;
} | {
    mov: null;
} | {
    mp4: null;
} | {
    webm: null;
} {
    return value == VideoFileType.avi ? {
        avi: null
    } : value == VideoFileType.mov ? {
        mov: null
    } : value == VideoFileType.mp4 ? {
        mp4: null
    } : value == VideoFileType.webm ? {
        webm: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThumbnailType): {
    autoGenerated: null;
} | {
    manualUpload: null;
} {
    return value == ThumbnailType.autoGenerated ? {
        autoGenerated: null
    } : value == ThumbnailType.manualUpload ? {
        manualUpload: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
